/*
 * SPDX-FileCopyrightText: 2026 mindreset
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

// 中文：走 epdiy LCD 输出路径的原始并口 EPD 驱动。与 LgfxEpdDriver 同一类面板
// （无片上控制器，MCU 逐行逐列打时序），区别在于时序由 LCD_CAM 硬件生成：
// XLE←HSYNC、XCL←PCLK、XSTL←DE，CKV 由 RMT 产生。LovyanGFX 的 i80 通道没有 DE
// 信号，这也是本板不用 LgfxEpd 的原因（read-pico.md §2.4 item 3 / blocker B4）。
//
// English: raw-parallel EPD driver over epdiy's LCD output path. Same panel class
// as LgfxEpdDriver (no on-glass controller, the MCU clocks every row/column), but
// the timing comes from the LCD_CAM hardware: XLE←HSYNC, XCL←PCLK, XSTL←DE, with
// CKV generated by RMT. LovyanGFX's i80 bus has no DE signal at all, which is why
// this board does not use the LgfxEpd driver (read-pico.md §2.4 item 3 / B4).
//
// 选中条件：-DFREEINK_DRIVER_EPDIY_LCD=1（由 FREEINK_DEVICE_READPICO 推出），
// 且该 env 的 lib_deps 里有 EpdiyLcd。板子必须用
// -DFREEINK_EPDIY_LCD_CONFIG=yourConfig 提供 const EpdiyLcdConfig& yourConfig()。
//
// Selection: linked only when -DFREEINK_DRIVER_EPDIY_LCD=1 (derived from
// FREEINK_DEVICE_READPICO) and EpdiyLcd is in that env's lib_deps. The board MUST
// supply a config via -DFREEINK_EPDIY_LCD_CONFIG=yourConfig.

#include <BoardConfig.h>

#include "PanelDriver.h"

// The whole header is inert unless this env links EpdiyLcd. Keeping the guard
// INSIDE the header (not only at the include site) matters: PlatformIO compiles
// every source of a library that any env uses, so EpdiyLcdDriver.cpp is built for
// X3/X4/C3 too — and there <EpdiyLcd.h> does not exist.
// / 整个头文件在未链接 EpdiyLcd 的 env 里必须完全失效。守卫必须放在头文件内部而
// 不只是 include 处：PlatformIO 会为任何使用该库的 env 编译它的全部源文件，所以
// EpdiyLcdDriver.cpp 在 X3/X4/C3 下也会被编译，而那些 env 里没有 <EpdiyLcd.h>。
#if FREEINK_DRIVER_EPDIY_LCD

#include <EpdiyLcd.h>

namespace freeink {

class EpdiyLcdDriver : public PanelDriver {
 public:
  explicit EpdiyLcdDriver(const EpdiyLcdConfig& cfg);

  uint32_t spiHz() const override { return 0; }  // epdiy owns the LCD_CAM bus
  BusyPolarity busyPolarity() const override { return BusyPolarity::ActiveLow; }
  bool usesExternalBus() const override { return true; }
  PanelGeometry geometry() const override;

  // MUST be declared. Every other driver in the tree reports its grayscale
  // encoding here; leaving this at the base-class default made the driver report
  // GrayscaleEncoding::Unsupported, and FreeInkDisplay::grayscaleCapabilities()
  // (FreeInkDisplay.cpp:682-688) filters on exactly that -- so the facade reported
  // "this panel has no grayscale" for a panel whose LSB/MSB + displayGray path is
  // fully implemented. Anything that selects its strategy from the descriptor
  // (strip uploads, combined base, async base) therefore bypassed this board.
  //
  // OverlayMasks is the truth: plane background 0 = black/white taken from the
  // B/W base, LSB set = dark, MSB set = light. base stays Separate because the host
  // pushes the B/W frame through display() before the grey commit overlays it.
  GrayscaleCapabilities grayscaleCapabilities(GrayscaleMode mode = GrayscaleMode::Overlay) const override;

  uint8_t* beginGrayscale16() override { return _ready ? epdiyLcdBeginGrayscale16() : nullptr; }
  bool commitGrayscale16(const uint8_t* bwProxy) override { return _ready && epdiyLcdCommitGrayscale16(bwProxy); }
  void cancelGrayscale16() override { epdiyLcdCancelGrayscale16(); }
  void begin(EpdBus& bus) override;
  void deepSleep(EpdBus& bus) override;
  void display(EpdBus& bus, const uint8_t* fb, const uint8_t* prev, RefreshMode mode, bool turnOff) override;
  void displayWithContext(EpdBus& bus, const uint8_t* fb, const uint8_t* prev, RefreshMode mode, bool turnOff,
                          RefreshContext context) override;
  void requestResync(uint8_t settlePasses) override;
  void abortPostRefresh() override { _lastBaseMode = EpdiyLcdRefresh::Half; }

  // 抗锯齿用整体平面路径（supportsStripGrayscale() 保持默认 false，于是宿主走
  // copyGrayscaleLsb/Msb + displayGrayBuffer）：先把两个选择平面存下来，提交时由
  // EpdiyLcd 用底图加中间灰合成。
  //
  // 这里必须实现 displayGray()，不能靠基类默认：默认实现会把传进来的 `fb` 当页面
  // 推上去，而那时它装的是最后一个选择平面（与页面互补），结果就是整屏负片。
  // 同一个坑在 LgfxEpdDriver.cpp:187-201 有记录。
  //
  // / Anti-aliasing uses the whole-plane path (supportsStripGrayscale() stays at the
  // default false, so the host runs copyGrayscaleLsb/Msb + displayGrayBuffer): stash
  // the two selector planes, and let EpdiyLcd compose base + mid gray on commit.
  //
  // displayGray() MUST be implemented, not left to the base class: the default
  // pushes the `fb` it is handed as if it were a page, but at that moment it holds
  // the last selector plane (the complement of the page), which renders as a
  // screen-wide negative. LgfxEpdDriver.cpp:187-201 records the same trap.
  void copyGrayscaleLsb(EpdBus& bus, const uint8_t* lsb) override;
  void copyGrayscaleMsb(EpdBus& bus, const uint8_t* msb) override;
  void displayGray(EpdBus& bus, const uint8_t* fb, bool turnOff, const unsigned char* lut, bool factoryMode) override;

  // Combined base: the B/W page is only STASHED here, and the grey commit presents
  // base + mid tones together in one waveform. Pushing the base first would cost a
  // second full panel refresh per anti-aliased page (and drive the frame through two
  // different profiles).
  // / Combined base: see above.
  void displayGrayscaleBaseWithContext(EpdBus& bus, const uint8_t* fb, RefreshMode fallback, bool turnOff,
                                       RefreshContext context) override;

 private:
  const EpdiyLcdConfig& _cfg;
  bool _ready = false;
  uint8_t* _lsb = nullptr;
  uint8_t* _msb = nullptr;
  // 灰度提交用底图那一帧的档位；换成别的档位会让整屏按新 LUT 重新驱动一遍（闪）。
  // / The gray commit reuses the base frame's profile; a different profile re-drives
  // the whole panel through the new LUT (a flash).
  EpdiyLcdRefresh _lastBaseMode = EpdiyLcdRefresh::Half;
};

PanelDriver& epdiyLcdDriver();

}  // namespace freeink

#endif  // FREEINK_DRIVER_EPDIY_LCD
